kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: {{ .Values.application.name }}-dr
  namespace: {{ .Values.application.nameSpace }}
spec:
  host: {{ .Values.Application.dns }}
  subsets:
    - labels:
        version: stable
      name: stable
    - labels:
        version: canary
      name: canary
