apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Application.name }}-svc-preview
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.Application.Name }}
