kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: {{ .Values.application.name }}-virtual-service
  namespace: {{ .Values.application.nameSpace }}
spec:
  hosts:
    - "{{ .Values.application.dns }}"
  gateways:
     - {{ .Values.application.nameSpace }}-ingress-gateway
  http:
    - name: primary
      route:
      - destination:
          host: {{ .Values.application.name }}-stable-svc.svc.cluster.local
          subset: stable
        weight: 100
      - destination:
          host: {{ .Values.application.name }}-canary-svc.svc.cluster.local
          subset: canary
        weight: 0