kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: {{ .Values.Application.name }}-virtual-service
  namespace: {{ .Values.Application.nameSpace }}
spec:
  hosts:
    - "{{ .Values.Application.dns }}"
  gateways:
     - {{ .Values.Application.nameSpace }}-ingress-gateway
  http:
    - route:
        - destination:
            host: {{ .Values.Application.name }}-svc.svc.cluster.local
            subset: stable
          weight: 100
        - destination:
            host: {{ .Values.Application.name }}-svc.svc.cluster.local
            subset: canary
          weight: 0