kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: {{ .Values.application.name }}-virtual-service
  namespace: {{ .Values.application.nameSpace }}
spec:
  hosts:
    - "*"
  gateways:
     - {{ .Values.application.nameSpace }}-ingress-gateway
  http:  
    - match:
      - uri:
          prefix: / 
    - name: primary
      route:
      - destination:
          host: {{ .Values.application.name }}-stable-svc
          subset: stable
        weight: 100
      - destination:
          host: {{ .Values.application.name }}-canary-svc
          subset: canary
        weight: 0